[package]
name = "rsx"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rsx"
path = "src/main.rs"

[dependencies]
rsx-machine = { path = "../machine" }
eframe = { version = "0.31", default-features = false, features = ["wgpu", "default_fonts"] }
egui = "0.31"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
png = "0.17"
cpal = "0.15"
gilrs = "0.11.2"
objc2-game-controller = { version = "0.3.2", features = ["GCController", "GCExtendedGamepad", "GCPhysicalInputProfile", "GCControllerButtonInput", "GCControllerAxisInput", "GCControllerDirectionPad", "GCControllerElement", "GCDevice"] }

[dev-dependencies]
tempfile = "3"
